q = input("请输入：")
q = int (q)
w = input("请输入：")
w = int (w)
e = input("请输入：")
e = int (e)
r = input("请输入：")
r = int (r)
t = input("请输入：")
t = int (t)
y = input("请输入：")
y = int (y)
u = input("请输入：")
u = int (u)
i = input("请输入：")
i = int (i)
o = input("请输入：")
o = int (o)
p = input("请输入：")
p= int (p)
a = (q+w+e+r+t+y+u+i+o+p)
print("总数为：",a)
b=max(q,w,e,r,t,y,u,i,o,p)
print("最大：",b)
c= a/10
print("平均：",c)